# Generated by Django 3.2.8 on 2022-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='user_profile_bio',
            field=models.TextField(default='This user has no Bio yet', max_length=200, null=True),
        ),
    ]
