# Generated by Django 3.2.8 on 2022-06-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_commentreplies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReplies',
        ),
    ]
