# Generated by Django 3.2.8 on 2022-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
